export const ADD_FRIEND = "ADD_FRIEND";
export const CHANGE_PAGINATION = "CHANGE_PAGINATION";
export const DELETE_FRIEND = "DELETE_FRIEND";
export const CHANGE_FAVOURITE_PREFERENCE = "CHANGE_FAVOURITE_PREFERENCE";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SORT_BY_FAVOURITE_ASC = "SORT_BY_FAVOURITE_ASC";
export const SORT_BY_FAVOURITE_DESC = "SORT_BY_FAVOURITE_DESC";
